### ISSUE TITLE
Support for Disqus

### ISSUE THREAD

**Issue by wheleph** [WingLim/hugo-tania#21]
I was trying to enable Disqus on my website that uses this theme by adding `disqusShortname: "wheleph-gitlab-io"` to my `config.yaml`. But I don't see any comment sections at the bottom of my posts.

Can you add support for Disqus? 

Here's the source code of my website: https://gitlab.com/wheleph/wheleph.gitlab.io

**Comment by WingLim** [comment]
Now, you can use disqus by adding:

```yaml
disqusShortname: your-short-name

params:
  comments:
    enabled: true
    provider: disqus
```
