### ISSUE TITLE
How to add an "about" to nav bar

### ISSUE THREAD

**Issue by hieu6** [WingLim/hugo-tania#59]
How do I add an about page to this theme?

Existing `config.yaml` for hugo-tania

```yaml
menu:
  header:
    - name: Posts
      url: "/posts/"
  footer:
    - name: RSS
      url: "/index.xml"
```

The below `config.yaml` works for me on other themes
```yaml
menu:
  main:
  - identifier: about
    name: about hugo
    url: /about/
    weight: -110
```

I have also tried to add `/content/about/_index.md` which works on other themes, but can't figure out how to make it work on this theme.

Any help or direction where to look next would be appreciated. Thank you!

**Comment by WingLim** [comment]
You should create `/content/about.md` or `/content/about/index.md`

`_index.md` is a speical file to hugo, not a page.

Then add it to header nav by this:
```yaml
menu:
  header:
    - name: About
      url: "/about/"
```
