### ISSUE TITLE
When I first click "Articles" page 's categories, it doesn't work.

### ISSUE THREAD

**Issue by moluuser** [WingLim/hugo-tania#66]
I must refresh the website, it can work.

**Comment by moluuser** [comment]
When it works, I refresh it again and it fails again

**Comment by thomasnotfound** [comment]
@moluuser Does this occur during local testing or after you've published your site?

**Comment by moluuser** [comment]
> @moluuser Does this occur during local testing or after you've published your site?

Both ways will appear. I use github and cloudflare page to publish my site.

**Comment by thomasnotfound** [comment]
> > @moluuser Does this occur during local testing or after you've published your site?
> 
> Both ways will appear. I use github and cloudflare page to publish my site.

What does your file structure look like? What does your Hugo config look like? What exactly is the problem - can you either showcase screenshots or provide us a link to your website?

**Comment by moluuser** [comment]
Hugo config:
```yaml
baseurl: "https://blog.moluuser.com"
languageCode: "en-us"
title: "moluuser's Blog"
theme: "hugo-tania"
paginate: 6
copyright: "CC BY-NC 4.0 {year} © moluuser"

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: "🍭"
  # Logo will show before the blog title on site navbar.
  titleLogo: 
  socialOptions:
    email: 
  enableFootnotes: true
  author: "moluuser"

  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: moluuser/blog_comments
      id: R_kgDOGmdZGg
      category:
        name: Announcements
        id: DIC_kwDOGmdZGs4CAeb1

  # Limit how many categories filter show above search input.
  maxCategoryToShow: 10
  mathjax: true
  
menu:
  header:
    - name: Articles
      url: "/articles/"
      weight: 1
    - name: Time
      url: "/time/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 3
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
    guessSyntax: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML","RSS", "JSON"]
```

The problem occurred at https://blog.moluuser.com/articles/

**Comment by moluuser** [comment]
Hugo config:
```yaml
baseurl: "https://blog.moluuser.com"
languageCode: "en-us"
title: "moluuser's Blog"
theme: "hugo-tania"
paginate: 6
copyright: ""

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: "🍭"
  # Logo will show before the blog title on site navbar.
  titleLogo: 
  socialOptions:
    email: 
  enableFootnotes: true
  author: ""

  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: 
      id: 
      category:
        name: Announcements
        id: 

  # Limit how many categories filter show above search input.
  maxCategoryToShow: 10
  mathjax: true
  
menu:
  header:
    - name: Articles
      url: "/articles/"
      weight: 1
    - name: Time
      url: "/time/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 3
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
    guessSyntax: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML","RSS", "JSON"]
```

This problem occurred at https://blog.moluuser.com/articles/
