### ISSUE TITLE
如何添加Twikoo评论系统！

### ISSUE THREAD

**Issue by Chenmoe** [WingLim/hugo-tania#70]
希望作者大佬能把Twikoo评论能添加进去！感谢了~

**Comment by WingLim** [comment]
尝试一下这个分支下的主题
https://github.com/WingLim/hugo-tania/tree/feat/support-twikoo

```yaml
comments:
    enabled: true
    provider: twikoo

    twikoo:
        id:
        # 默认 ap-shanghai
        region:
        # 默认 window.location.pathname
        path:
        # 默认 zh-CN
        lang:  
```
你试一下是否能用
